
stages:
  - chaos
  - post-chaos

variables:
  GIT_DEPTH:                       1

.chaos-docker-release:            &chaos-docker-release
  stage:                           chaos
  only:
    - harry/chaostest-init
  tags: 
    - kubernetes-parity-build
  variables:
    PRODUCT:                       substrate
    DOCKERFILE:                    $PRODUCT.Dockerfile
    CONTAINER_IMAGE:               parity/$PRODUCT
  environment:
    name:                          parity-chaosnet
  image:                           docker:stable
  services:
    - docker:dind
  before_script:
    - test "$Docker_Hub_User_Parity" -a "$Docker_Hub_Pass_Parity"
        || ( echo "no docker credentials provided"; exit 1 )
    - docker login -u "$Docker_Hub_User_Parity" -p "$Docker_Hub_Pass_Parity"
    - docker info
  script:
    - cd ./artifacts/$PRODUCT/
    - VERSION="$(cat ./VERSION)"
    - echo "${PRODUCT} version = ${VERSION}"
    - test -z "${VERSION}" && exit 1
    - docker build
      --build-arg VCS_REF="${CI_COMMIT_SHA}"
      --build-arg BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
      --tag $CONTAINER_IMAGE:$VERSION
      --file $DOCKERFILE .
    - docker push $CONTAINER_IMAGE:$VERSION
    - docker logout

.chaos-test-singlenodeheight:
  stage:                           chaos
  <<:                              *chaos-docker-release
  only:
    - harry/chaostest-init
  tags: 
    - kubernetes-parity-build
  variables:
    PRODUCT:                       substrate
    DOCKERFILE:                    $PRODUCT.Dockerfile
    CONTAINER_IMAGE:               parity/$PRODUCT
  environment:
    name:                          parity-chaosnet
  image:                           parity/kubetools:latest
  script:
    - cd ./artifacts/$PRODUCT/
    - VERSION="$(cat ./VERSION)"
    - echo "${PRODUCT} version = ${VERSION}"
    - test -z "${VERSION}" && exit 1
    - cd ./chaostest
    - npm link
    - chaostest singlenodeheight -i $CONTAINER_IMAGE:$VERSION


.post-chaos-cleanup:
  stage:                           post-chaos
  only:
    - harry/chaostest-init
  tags: 
    - kubernetes-parity-build
  variables:
    PRODUCT:                       substrate
    DOCKERFILE:                    $PRODUCT.Dockerfile
    CONTAINER_IMAGE:               parity/$PRODUCT
  environment:
    name:                          parity-chaosnet
  image:                           docker:stable
  services:
    - docker:dind
  before_script:
    - test "$Docker_Hub_User_Parity" -a "$Docker_Hub_Pass_Parity"
        || ( echo "no docker credentials provided"; exit 1 )
    - docker login -u "$Docker_Hub_User_Parity" -p "$Docker_Hub_Pass_Parity"
    - docker info
  script:
    - docker rmi $CONTAINER_IMAGE:$VERSION -f
    - docker logout
  