[package]
name = "sp-session"
version = "2.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Primitives for sessions"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
sp-api = { version = "2.0.0-dev", default-features = false, path = "../api" }
sp-core = { version = "2.0.0-dev", default-features = false, path = "../core" }
sp-std = { version = "2.0.0-dev", default-features = false, path = "../std" }
sp-staking = { version = "2.0.0-dev", default-features = false, path = "../staking" }
sp-runtime = { version = "2.0.0-dev", default-features = false, path = "../runtime" }

hash-db = { version = "0.15.2", default-features = false }
trie-db = { version = "0.20.1", default-features = false }
sp-io = { version = "2.0.0-dev",  default-features = false, path = "../../primitives/io"}

[features]
default = [ "std" ]
std = [
	"codec/std",
	"sp-api/std",
	"sp-core/std",
	"sp-std/std",
	"sp-staking/std",
	"sp-runtime/std",
]
